@startmindmap
* software\nquality
 * project
  * scope triangle
  * development life cycle
   *_ requirements
   *_ documentation
 * development
  * toolchain
  * local environmnet
  * design
   * architecture
   * type systems
    *_ static
    *_ dynamic
    *_ weak
    *_ strong
   * DDD 
   * Acronyms
    *_ SOLID
    *_ DRY
    *_ KISS
    *_ YAGNI
  * formal verification
  * testing
   * types
    *_ unit test
    *_ integration test
    *_ performance
    *_ load
   * approach
    *_ TDD
    *_ Fuzzing
    *_ BDD
   * Mock
 * runtime
  * maintaning
  * logging
  * troubleshooting
  * debugging
  * A/B testing
  * monitoring
  * pagerduty
@endmindmap
